services:
  web:
    image: nginx:alpine
    restart: unless-stopped
    expose:
      - 80
    volumes:
      - ./site:/usr/share/nginx/html:ro
    networks:
      - nginx-network

networks:
  nginx-network:
    external: true